### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nmeylan** [nmeylan/RORganize-Plugin-Agile-Board#1]
Version 1.0 : Definition of Done
- [x] Icon creation (for plan, epics, sprint, user story, agile...)
- [x] Create board
 - [x] Menu
  - [x] Plan
   - [x] Display mode (unified / split)
    - [x] Work
    - [x] Configuration
       - [x] Define points
       - [x] Define status
       - [x] Epics
- [x] User story
 - [x] CRUD
  - [x] Create new issue (with a simple view)
  - [x] Remove attached issues.
 - [x] Drag and drop
   - [x] Change sprint
    - [x] Prioritization
 - [x] Link with issues  
    - [x] Change sprint version should change issue version
    - [x] Change story category should change issue category
    - [x] Change story status should change issue status
    - [x] Change story tracker should change issue tracker
- [x] Sprint
 - [x] CRUD
 - [x] Include backlog

- [x] Story map
 - [x] Display story
 - [x] Update progression
 - [x] Filter (choose sprint : by default currents/ path params sprint id)
- [x] Journalizable
- [x] Commentable
- [x] Watchable
- [x] Notifiable (in app / email)
- [x] Permissions
 - [x] Epics
 - [x] US
 - [x] Configure board

- [x] Filters : a simple js filter (on title, epics, category)
  - [x] Apply filter when user click on story info (epic, category, status, tracker)
  - [x] Provide a way to share filters (maybe use anchor)
  - [x] Update sprints informations when filters are applied (stories counter / points counter)
- [x] Report
 - [x] Archive sprint / view archives
 - [x] Report : sprint health (points progress, time elapse, work complete )
 - [x] Report : sprint burndown chart

- [x] Attach existing issue
- [x] Code review / refactoring !
