### ISSUE TITLE
Todo release 1.1 (Responsive Design)

### ISSUE THREAD

**Issue by nmeylan** [nmeylan/RORganize-Plugin-Agile-Board#3]
Follow core modifications : see RORganize/issues/3
- [ ] Refactor javascript way of binding (replace js.erb with a binding system based on scope)
  - [ ] Board
  - [ ] Epic
  - [ ] Sprint
  - [ ] Points
  - [ ] Reports
  - [ ] User stories
  - [ ] Stories statuses
- [x] Refactor forms with simple form
- [ ] Refactor all handmade css with bootstrap
  - [ ] Use navbar component
  - [ ] Use modal component
  - [ ] Use button group 
  - [ ] Use dropdown
  - [ ] Use navtab
  - [ ] Use grid
  - [ ] Use collapse
  - [ ] Use tooltip
  - [ ] Use progressbar
  - [ ] Responsive sidebar
